export type DashboardGame = 'ETS2' | 'ATS';
export type DashboardOrientation = 'landscape' | 'portrait' | 'both';
export type DashboardResolution = '720p' | '1080p' | '1440p' | 'any';

export type DASHBOARD_DATA_TYPE = {
  id: string;
  title: string;
  description: string;
  brand: string;
  game: DashboardGame;
  image: string | null;

  // ── UI / preferencias
  rating: number;
  isNew: boolean;

  // ── capacidades técnicas
  orientation: DashboardOrientation;
  resolutions: DashboardResolution[];
  hasDarkMode: boolean;
};

const DESC =
  'Interfaz optimizada para telemetría de alta precisión y baja latencia.';

/**
 * Imagen por defecto para dashboards que no tienen captura aún.
 */
export const DEFAULT_PLACEHOLDER_IMAGE = require('../assets/images/dashPlaceholder.png');

export const dashboardDataSeed: DASHBOARD_DATA_TYPE[] = [
  // ── ETS2 · DAF
  {
    id: 'dash-0',
    title: 'DAF XF105',
    brand: 'DAF',
    game: 'ETS2',
    image: null,
    rating: 3.8,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-1',
    title: 'DAF XF Euro 6',
    brand: 'DAF',
    game: 'ETS2',
    image: null,
    rating: 4.0,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-2',
    title: 'DAF NGD XG+',
    brand: 'DAF',
    game: 'ETS2',
    image: null,
    rating: 4.5,
    isNew: true,
    orientation: 'landscape',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-3',
    title: 'DAF XD',
    brand: 'DAF',
    game: 'ETS2',
    image: null,
    rating: 4.1,
    isNew: false,
    orientation: 'both',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  // ... resto de dashboards se mantienen igual (usando null por ahora)
  {
    id: 'dash-4',
    title: 'Iveco Stralis',
    brand: 'Iveco',
    game: 'ETS2',
    image: null,
    rating: 3.5,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-5',
    title: 'Iveco Stralis Hi-Way',
    brand: 'Iveco',
    game: 'ETS2',
    image: null,
    rating: 3.9,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-6',
    title: 'Iveco S-Way',
    brand: 'Iveco',
    game: 'ETS2',
    image: null,
    rating: 4.3,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-7',
    title: 'MAN TGX Euro 5',
    brand: 'MAN',
    game: 'ETS2',
    image: null,
    rating: 3.7,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-8',
    title: 'MAN TGX Euro 6',
    brand: 'MAN',
    game: 'ETS2',
    image: null,
    rating: 4.1,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-9',
    title: 'MAN TGX 2020',
    brand: 'MAN',
    game: 'ETS2',
    image: null,
    rating: 4.4,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-10',
    title: 'Mercedes-Benz Actros MP3',
    brand: 'Mercedes-Benz',
    game: 'ETS2',
    image: null,
    rating: 3.9,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-11',
    title: 'Mercedes-Benz Actros MP4',
    brand: 'Mercedes-Benz',
    game: 'ETS2',
    image: null,
    rating: 4.2,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-12',
    title: 'Renault Magnum',
    brand: 'Renault',
    game: 'ETS2',
    image: null,
    rating: 3.6,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-13',
    title: 'Renault Premium',
    brand: 'Renault',
    game: 'ETS2',
    image: null,
    rating: 3.8,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-14',
    title: 'Renault T Evolution',
    brand: 'Renault',
    game: 'ETS2',
    image: null,
    rating: 4.3,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-15',
    title: 'Renault E-Tech T Electric',
    brand: 'Renault',
    game: 'ETS2',
    image: null,
    rating: 4.7,
    isNew: true,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-16',
    title: 'Scania R 2009',
    brand: 'Scania',
    game: 'ETS2',
    image: null,
    rating: 3.9,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-17',
    title: 'Scania Streamline',
    brand: 'Scania',
    game: 'ETS2',
    image: null,
    rating: 4.2,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-18',
    title: 'Scania R',
    brand: 'Scania',
    game: 'ETS2',
    image: null,
    rating: 4.5,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-19',
    title: 'Scania S',
    brand: 'Scania',
    game: 'ETS2',
    image: null,
    rating: 4.8,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-20',
    title: 'Scania S Electric',
    brand: 'Scania',
    game: 'ETS2',
    image: null,
    rating: 4.9,
    isNew: true,
    orientation: 'landscape',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-21',
    title: 'Volvo FH3 Classic',
    brand: 'Volvo',
    game: 'ETS2',
    image: null,
    rating: 3.7,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-22',
    title: 'Volvo FH4',
    brand: 'Volvo',
    game: 'ETS2',
    image: null,
    rating: 4.1,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-23',
    title: 'Volvo FH5',
    brand: 'Volvo',
    game: 'ETS2',
    image: null,
    rating: 4.6,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-24',
    title: 'Volvo FH6',
    brand: 'Volvo',
    game: 'ETS2',
    image: null,
    rating: 4.9,
    isNew: true,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-25',
    title: 'Freightliner Cascadia 2019',
    brand: 'Freightliner',
    game: 'ATS',
    image: null,
    rating: 4.2,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-26',
    title: 'Freightliner Cascadia 2025',
    brand: 'Freightliner',
    game: 'ATS',
    image: null,
    rating: 4.7,
    isNew: true,
    orientation: 'landscape',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-27',
    title: 'Kenworth T680 Classic',
    brand: 'Kenworth',
    game: 'ATS',
    image: null,
    rating: 4.0,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-28',
    title: 'Kenworth T680 Next Gen',
    brand: 'Kenworth',
    game: 'ATS',
    image: null,
    rating: 4.5,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-29',
    title: 'Kenworth W900',
    brand: 'Kenworth',
    game: 'ATS',
    image: null,
    rating: 4.3,
    isNew: false,
    orientation: 'portrait',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-30',
    title: 'Peterbilt 389',
    brand: 'Peterbilt',
    game: 'ATS',
    image: null,
    rating: 4.4,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-31',
    title: 'Peterbilt 579 Classic',
    brand: 'Peterbilt',
    game: 'ATS',
    image: null,
    rating: 4.6,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-32',
    title: 'Mack Anthem',
    brand: 'Mack',
    game: 'ATS',
    image: null,
    rating: 4.1,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-33',
    title: 'Mack Pinnacle',
    brand: 'Mack',
    game: 'ATS',
    image: null,
    rating: 3.9,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-34',
    title: 'International LoneStar',
    brand: 'International',
    game: 'ATS',
    image: null,
    rating: 4.0,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-35',
    title: 'International LT',
    brand: 'International',
    game: 'ATS',
    image: null,
    rating: 4.2,
    isNew: false,
    orientation: 'both',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-36',
    title: 'International 9900i Eagle',
    brand: 'International',
    game: 'ATS',
    image: null,
    rating: 4.4,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-37',
    title: 'Western Star 49X',
    brand: 'Western Star',
    game: 'ATS',
    image: null,
    rating: 4.3,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-38',
    title: 'Western Star 57X',
    brand: 'Western Star',
    game: 'ATS',
    image: null,
    rating: 4.5,
    isNew: true,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-39',
    title: 'Western Star 5700XE',
    brand: 'Western Star',
    game: 'ATS',
    image: null,
    rating: 4.1,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: false,
    description: DESC,
  },
  {
    id: 'dash-40',
    title: 'Volvo VNL 2018',
    brand: 'Volvo',
    game: 'ATS',
    image: null,
    rating: 4.0,
    isNew: false,
    orientation: 'landscape',
    resolutions: ['720p', '1080p'],
    hasDarkMode: true,
    description: DESC,
  },
  {
    id: 'dash-41',
    title: 'Volvo VNL 2024',
    brand: 'Volvo',
    game: 'ATS',
    image: null,
    rating: 4.8,
    isNew: true,
    orientation: 'both',
    resolutions: ['1080p', '1440p'],
    hasDarkMode: true,
    description: DESC,
  },
];
